### PR TITLE
Update balena sdk

### PR DESCRIPTION
**Pull request by zwhitchcox**
Fixes [EOF zlib issue](https://github.com/balena-io/balena-cli/issues/2152 ) per [@klutchell 's balena-request fix](https://github.com/balena-io-modules/balena-request/pull/156).

See: https://github.com/madler/zlib/blob/master/FAQ#L33

Change-type: minor

### CODE REVIEW

**Comment by zwhitchcox** [comment]
Once this is merged, we can merge this into the cli

**Comment by klutchell** [comment]
I already have a [PR](https://github.com/balena-io/balena-cli/pull/2315) to bump the SDK in the CLI, but I guess it needs to be bumped here as well.

However when I tested teh `Z_SYNC_FLUSH` change, we didn't get the `Z_BUF_ERROR` but the downloaded file was incomplete. If you're testing this you need to compare the `md5sum` to a sane download.

**Comment by zwhitchcox** [comment]
@klutchell Hmm, that's weird, I just tried with the current version on my rpi4 (`aarch64`), and the. md5 sums were the same as on my mac. Do I need to use a rpi3?

**Comment by zwhitchcox** [comment]
Oh, nvmd, I guess you were probably using raspbian 32-bit

**Comment by klutchell** [comment]
> Oh, nvmd, I guess you were probably using raspbian 32-bit

@zwhitchcox Did you have any luck reproducing this on a 32-bit ARM device like a Pi3?

**Comment by zwhitchcox** [comment]
@klutchell I tried, but I couldn't get either of my raspberry pi 3s to come up...even with raspbian....I guess I could try just installing Rasbpian one of my rpi4s...it might not be till next week till I have a chance to do that though.

**Pull request closed without merging**
